language: python
#python:
#  - "2.1"
#  - "2.2"
#  - "2.3"
#  - "2.4"
#  - "2.5"
#  - "2.6"
#  - "2.7"
#  - "3.0"
#  - "3.1"
#  - "3.2"
#  - "3.3"
#  - "pypy"
# command to install dependencies
install: pip install tox --use-mirrors
# command to run tests
script: tox
